# Generated by Django 5.1.3 on 2024-11-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id_cuidador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_espanol', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado_conservacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id_habitat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('clima', models.CharField(max_length=50)),
                ('vegetacion', models.CharField(max_length=100)),
                ('continente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id_itinerario', models.AutoField(primary_key=True, serialize=False)),
                ('duracion', models.DurationField()),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_visitantes', models.IntegerField()),
                ('num_especies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('extension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CuidadorEspecie',
            fields=[
                ('id_cuidador_especie', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('id_cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.cuidador')),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.especie')),
            ],
        ),
        migrations.CreateModel(
            name='EspecieHabitat',
            fields=[
                ('id_especie_habitat', models.AutoField(primary_key=True, serialize=False)),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.especie')),
                ('id_habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.habitat')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaItinerario',
            fields=[
                ('id_guia_itinerario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=50)),
                ('id_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.guia')),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.itinerario')),
            ],
        ),
        migrations.CreateModel(
            name='ItinerarioZona',
            fields=[
                ('id_itinerario_zona', models.AutoField(primary_key=True, serialize=False)),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.itinerario')),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.zona')),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.zona'),
        ),
    ]
