# Generated by Django 5.1.3 on 2024-11-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_especies_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuidador',
            old_name='id_cuidador',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cuidadorespecie',
            old_name='id_cuidador_especie',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='id_especie',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='especiehabitat',
            old_name='id_especie_habitat',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='id_guia',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='guiaitinerario',
            old_name='id_guia_itinerario',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='habitat',
            old_name='id_habitat',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='itinerario',
            old_name='id_itinerario',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='itinerariozona',
            old_name='id_itinerario_zona',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='id_zona',
            new_name='id',
        ),
    ]
