# Generated by Django 5.1.3 on 2024-11-28 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_especies_control', '0002_rename_id_cuidador_cuidador_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='id_zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo_especies_control.zona'),
        ),
    ]
